### ISSUE TITLE
Filtering on simulation status is not yet working as intended.

### ISSUE THREAD

**Issue by tmadlener** [key4hep/dmx#30]
In order to not blow up #27 too much, I have pulled this into a separate issue that can then also be fixed by a separate PR.

The sim status filtering is not currently working as intended. If I look here (which I hope is the right place):

https://github.com/key4hep/dmx/blob/23a1eb2cc4ed4fb3200a4d38ee70e464a180a21f/js/menu/filter/parameters.js#L114-L118

This checks whether the sim status is exactly the value of the check boxes that appear on the page:
![image](https://github.com/key4hep/dmx/assets/16774861/73e7b759-578d-4bcb-be66-bafe9e583e99)

However, these are the bits in the sim status that are set if a condition is met:
https://github.com/key4hep/EDM4hep/blob/0784e02caf09ee89a728b4dd17ed74ef082e4d66/edm4hep.yaml#L297-L304

So there are two things that would need to be improved / fixed
1. The current display should not display the bit numbers, but rather their meaning. E.g. `23` -> `Overlay`
2. The actual filtering should be checking the bits of the simulator status, not the actual value

**Comment by brauliorivas** [comment]
> 1. The current display should not display the bit numbers, but rather their meaning. E.g. `23` -> `Overlay`

This seems easy to implement. However, there are cases when the bit is completely different from the [specification](https://github.com/key4hep/EDM4hep/blob/0784e02caf09ee89a728b4dd17ed74ef082e4d66/edm4hep.yaml#L297-L304) (like 0 or some other number). In that case, what should be displayed?



> 2\. The actual filtering should be checking the bits of the simulator status, not the actual value

Sorry, I don't quite understand what you mean by "not the actual value"? I mean, the condition checks if `simStatus` is the same as the `simStatus` of the particle.

**Comment by tmadlener** [comment]
To clarify what I mean by *not the value*, the check that is currently there is effectively

```js
return particle.simStatus === filterSimStatus;
```

Where `filterSimStatus` is taken from the input (i.e. something between 23 and 30 inclusive). However, what we would actually want to have is a check like this

```js
return (particle.simStatus & (1 << filterSimStatus)) !== 0;
```

This way the filter would check whether a certain bit is set in `simStatus`. I suppose you would have to introduce a new class inheriting from `FilterParameter` that works similar to the `Checkbox` does now, but has a different implementation for `buildCondition`. Alternatively, subclass the `Checkbox` and make a `ValueCheckbox` (that keeps the current behavior) and a `BitfieldCheckbox` that implements the proposed behavior here.

**Comment by brauliorivas** [comment]
Ohh so it's not a direct comparison. Instead, some math to check the status. I've implemented these changes in this [commit](https://github.com/key4hep/dmx/pull/27/commits/27697644ab9f590d88ae6e0b46d2bfdd91c14d75). The new check works as intended, by making the bit operations, and shows the simulation status name (overlay, stopped, etc) if the `simStatus` of the particle is defined [here](https://github.com/key4hep/EDM4hep/blob/0784e02caf09ee89a728b4dd17ed74ef082e4d66/edm4hep.yaml#L297-L304). However, I show the number instead if the `simStatus` is not found.

**Comment by brauliorivas** [comment]
I just noticed that I confused `simStatus` with `genStatus`. `genStatus` was using the `simStatus` implementation and vice versa. But now is fixed.
