### ISSUE TITLE
Add possibility to filter MCParticles via generatorStatus

### ISSUE THREAD

**Issue by tmadlener** [key4hep/dmx#31]
Similar to the simulator status it might be useful to filter on the generator status. This would allow it to filter out all the intermediate states that are present, e.g. during hadronization.

In this case the inputs are not as clear cut as for the simulation status, so we would probably need a list of input values to filter(?). Or potentially even the possibility for a user defined filter condition, based on the status value(?).

**Comment by brauliorivas** [comment]
So, to filter by generator status, does it have some special rules like simulator status? 

> we would probably need a list of input values to filter

Currently, the values are listed based on the data. It means it reads every particle and extract a set of unique values.

> Or potentially even the possibility for a user defined filter condition, based on the status value(?).

Right now, the simplest way to filter by generator status is by checking if the particle genStatus is the same as in the filter. What else do you think that we could add?

**Comment by tmadlener** [comment]
I was thinking about something like an expression, that can use the `generatorStatus` value, e.g. an input field, where I could put in something like

```js
(generatorStatus !== 52) || (generatorStatus === 23)
```

I.e. something that is not easily possible with just the checkboxes. However, we could also wait with that until someone actually has a use case for this instead of pre-emptively implementing things that are not necessary.
