### ISSUE TITLE
PDG -5122 is not mapped to a particle

### ISSUE THREAD

**Issue by tmadlener** [key4hep/dmx#39]
This is a minor issue I just stumbled over when looking at the prieview. The PDG code `-5122` is not mapped to a particle name
![image](https://github.com/key4hep/dmx/assets/16774861/ebde6274-7da6-4a6d-b4e2-6455e2ec6d58)

This can be reproduced with event 1 in the example file where it appears in row 11.

**Comment by brauliorivas** [comment]
Good! According to `LCIO`, both positive and negative pdg have the same [symbol](https://github.com/iLCSoft/LCIO/pull/170/files#diff-ab79a6d4ac8ba0c3dc5f899a764751693e8f8117e7e972f8a157c9a5009739c5R546-R547). Is this correct? Then I'll add it immediately.

**Comment by tmadlener** [comment]
Technically it should be `\bar{\Lambda_{b}^{0}}`, i.e. with a bar on top, because it's not its own anti-particle. Overall negative numbers are by convention the anti-particles, which are denoted via a bar on top of things
