### ISSUE TITLE
Display quark charges as fractions

### ISSUE THREAD

**Issue by Zehvogel** [key4hep/dmx#6]
to avoid this
![image](https://github.com/key4hep/dmx/assets/12029880/a955e28f-8497-4aed-be0d-b9f4dd5046af)

**Comment by kjvbrt** [comment]
Hi @Zehvogel the https://github.com/key4hep/dmx/pull/7 should fix the issue.

**Comment by Zehvogel** [comment]
almost, but the 2/3 charge does not work yet

![image](https://github.com/key4hep/dmx/assets/12029880/549e9fa4-5e4e-4c98-b50d-f113f934cfe4)

![image](https://github.com/key4hep/dmx/assets/12029880/6cda79e8-32b9-4ab8-8419-bf865507e8a7)

**Comment by kjvbrt** [comment]
https://github.com/key4hep/dmx/pull/8 ?

**Comment by Zehvogel** [comment]
yes thx!
